name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  pull_and_deploy:
    name: Git Pull and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          
      - name: Git pull and restart processes
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER }} './pull-and-restart-process.sh'
